
platform :ios, '8.0'
use_frameworks!

target ‘PhotoService’ do

  pod 'FMDB/SQLCipher'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'ShareSDK3'
  pod 'ReactiveObjC'
  pod 'SDWebImage', '~> 4.1.0'
  pod 'Base64'
  #图片选择
  pod 'CBPic2ker'
 # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'



end
